extends Node

signal score_changed(new_score: int)
signal run_reset()
signal run_completed()
signal run_failed(message: String)
signal message_shown(message: String)
signal player_moved(position: Vector2)
signal app_shell_ready()
signal settings_loaded()
signal settings_changed()
signal audio_settings_applied()
signal scene_change_started(scene_path: String)
signal scene_changed(scene_path: String)
signal scene_change_failed(scene_path: String, error_code: int)
signal session_state_changed(session_state: String)
signal start_game_requested()
signal open_options_requested()
signal open_credits_requested()
signal open_shader_showcase_requested()
signal back_to_menu_requested()
signal pause_requested()
signal resume_game_requested()
signal restart_run_requested()
signal toggle_debug_requested()
