param(
    [string]$ProjectPath = (Get-Location).Path,
    [string]$ProjectName = "Godot Game"
)

$ErrorActionPreference = "Stop"

$script:Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-TextFile {
    param(
        [string]$Path,
        [string]$Value
    )
    [System.IO.File]::WriteAllText($Path, $Value, $script:Utf8NoBom)
}

if (-not (Test-Path -LiteralPath $ProjectPath)) {
    New-Item -ItemType Directory -Path $ProjectPath | Out-Null
}

$resolvedProject = (Resolve-Path -LiteralPath $ProjectPath).ProviderPath
$projectFile = Join-Path $resolvedProject "project.godot"
if (Test-Path -LiteralPath $projectFile) {
    throw "project.godot already exists at $projectFile"
}

$dirs = @(
    "game/main",
    "game/boot",
    "game/autoload",
    "features/player",
    "features/ui/hud",
    "features/levels/level_001",
    "shared/components",
    "shared/resources",
    "shared/states",
    "shared/utils",
    "assets/runtime/sprites",
    "assets/runtime/tilesets",
    "assets/runtime/models",
    "assets/runtime/textures",
    "assets/runtime/ui",
    "assets/runtime/vfx",
    "assets/runtime/shaders",
    "assets/runtime/audio/music",
    "assets/runtime/audio/sfx",
    "assets/runtime/audio/ambience",
    "assets/runtime/fonts",
    "assets/source/art",
    "assets/source/audio",
    "assets/source/blender",
    "assets/source/aseprite",
    "assets/source/references",
    "assets/import_presets",
    "addons",
    "docs/specs/qa",
    "docs/decisions",
    "docs/production/stories",
    "tests/unit",
    "tests/integration",
    "tests/e2e",
    "tools/godot",
    "tools/asset_pipeline",
    "tools/ci",
    "exports"
)

foreach ($dir in $dirs) {
    $fullPath = Join-Path $resolvedProject $dir
    if (-not (Test-Path -LiteralPath $fullPath)) {
        New-Item -ItemType Directory -Path $fullPath | Out-Null
    }
}

$escapedName = $ProjectName.Replace('"', '\"')

Write-TextFile -Path $projectFile -Value @"
; Engine configuration file.
; This file is generated by godot-game-studio-agent for Godot 4.7.

config_version=5

[application]

config/name="$escapedName"
run/main_scene="res://game/main/main.tscn"
config/features=PackedStringArray("4.7", "GL Compatibility")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[rendering]

renderer/rendering_method="gl_compatibility"
textures/canvas_textures/default_texture_filter=0
"@

Write-TextFile -Path (Join-Path $resolvedProject "game/main/main.tscn") -Value @"
[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://game/main/main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")

[node name="Label" type="Label" parent="."]
offset_left = 24.0
offset_top = 24.0
offset_right = 620.0
offset_bottom = 72.0
text = "Godot 4.7 production project ready."
"@

Write-TextFile -Path (Join-Path $resolvedProject "game/main/main.gd") -Value @"
extends Node2D

func _ready() -> void:
	print("Godot 4.7 production project ready.")
"@

Write-TextFile -Path (Join-Path $resolvedProject "docs/.gdignore") -Value "Documentation only."
Write-TextFile -Path (Join-Path $resolvedProject "assets/source/.gdignore") -Value "Editable source assets only."
Write-TextFile -Path (Join-Path $resolvedProject "tools/.gdignore") -Value "External tools only."

Write-Host "Created Godot 4.7 production project at $resolvedProject"
